### ISSUE TITLE
Pressing Cancel in "Select the type this attribute is" dialog crashes the program

### ISSUE THREAD

**Issue by bjornpijnacker** [andrewlalis/EntityRelationMappingEditor#3]
Creating an attribute, then pressing cancel in the "select the type this attribute is" yields a NullPointerException. NullPointerExceptions are also thrown on any further interaction with the panel (not the menu bar) which makes the program unusable.

https://user-images.githubusercontent.com/35508080/107200613-36600380-69f8-11eb-83a0-4dac45953ad7.mp4

**Comment by andrewlalis** [comment]
Thanks, it looks like I forgot some null checks. Will fix it shortly.
