### ISSUE TITLE
Popup dialogs not bound to main frame

### ISSUE THREAD

**Issue by bjornpijnacker** [andrewlalis/EntityRelationMappingEditor#9]
Currently (for me) popups are spawned in the center of my primary display. This behavior is annoying when the mapping editor isn't on my primary display. Better would be to parent the dialogs to the main frame of the application so that they spawn wherever the application is.

PS: I can submit a PR for this as well, if you want me to

**Comment by andrewlalis** [comment]
Yeah, it would be great if you could address that. Sadly just setting the dialogs to modal doesn't seem to do the trick.

**Comment by bjornpijnacker** [comment]
I'll look into it. I won't be able to finish it before Tuesday at least, seeing as I'm in the middle of moving and I don't have my second display available for testing.

**Comment by bjornpijnacker** [comment]
I was able to test it by checking popups appear in the center of the panel instead of the display
